package com.oracle.ateam.threadlogic.advisories;

public enum ThreadType {

  SOA, IWAY, JMS_ADAPTER, AQ_ADAPTER, LDAP, COHERENCE, IAS_CACHE, ORCL, TIMER, MERCURY_DIAGNOSTICS, WILY, WLS_JMS, WLS_MUXER, WLS_EMBEDDED_LDAP, WLS_TIMER, WLS, JVM, GC, FINALIZER, MISC_VM, CUSTOM_POOL, UNKNOWN;
}
